databases:
  - name: colaborators
    databaseName: colaborators
    user: colaborators
    plan: free

services:
  - type: web
    name: colaborators
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: colaborators
        property: connectionString
    - key: RAILS_MASTER_KEY
      sync: false
    - key: WEB_CONCURRENCY
      value: 2

